# -*- coding: utf-8 -*-
"""choosing_the_number_of_neighbors.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J1RfGAJQJUQFybw6EZIcRx4NUhgQTcmU
"""

import pandas as pd
from sklearn.model_selection import KFold
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import scale

df = pd.read_table('_805605c804bae8c5c24785f433b230ce_wine.data', 
                   sep=',', 
                   index_col=False,
                   names=[1,2,3,4,5,6,7,8,9,10,11,12,13,14])

y = df[1]
features = [2,3,4,5,6,7,8,9,10,11,12,13,14]
x = df[features]

arr = []
for i in range(1, 51):
    kfold = KFold(n_splits=5, shuffle=True, random_state=42)
    model = KNeighborsClassifier(n_neighbors=i)
    scores = cross_val_score(model, x, y, cv=kfold, scoring='accuracy')
    arr.append(scores.mean())
arr

x = scale(x)
arr = []
for i in range(1, 31):
    kfold = KFold(n_splits=5, shuffle=True, random_state=42)
    model = KNeighborsClassifier(n_neighbors=i)
    scores = cross_val_score(model, x, y, cv=kfold, scoring='accuracy')
    arr.append(scores.mean())
arr