# -*- coding: utf-8 -*-
"""first_lesson_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mGzaZTv9EixiDmW9TD4Z9kRN6VtBZ8hy
"""

import pandas as pd
reviews = pd.read_csv("winemag-data_first150k.csv", index_col=0)
import seaborn as sns

sns.countplot(reviews['points'])

sns.kdeplot(reviews.query('price < 200').price)

reviews[reviews['price'] < 200]['price'].value_counts().sort_index().plot.line()

sns.kdeplot(reviews[reviews['price'] < 200].loc[:, ['price', 'points']].dropna().sample(5000))

sns.distplot(reviews['points'], bins=10, kde=False)

sns.jointplot(x='price', y='points', data=reviews[reviews['price'] < 100])

sns.jointplot(x='price', y='points', data=reviews[reviews['price'] < 100], kind='hex', 
              gridsize=20)

df = reviews[reviews.variety.isin(reviews.variety.value_counts().head(5).index)]

sns.boxplot(
    x='variety',
    y='points',
    data=df
)

sns.violinplot(
    x='variety',
    y='points',
    data=reviews[reviews.variety.isin(reviews.variety.value_counts()[:5].index)]
)