# -*- coding: utf-8 -*-
"""Titanic_task_for_kaggle.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KWWx_TGC7nf4VHEY41dcKNCDZqAUw1e6
"""

import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.impute import SimpleImputer

train_data = 'train.csv'
test_data = 'test.csv'
train_df = pd.read_csv(train_data)
test_df = pd.read_csv(test_data)

train_df['Sex'] = train_df['Sex'] == 'male'
test_df['Sex'] = test_df['Sex'] == 'male'
y = train_df['Survived'].values
features = ['Pclass', 'Age', 'Fare', 'SibSp', 'Parch', 'Sex']
x = train_df[features].values
test_x = test_df[features].values

my_imputer = SimpleImputer()
x = my_imputer.fit_transform(x)
test_x = my_imputer.transform(test_x)

dt = RandomForestClassifier(n_estimators=1000, random_state=1)
dt.fit(x, y)
predictions = dt.predict(test_x)

output = pd.DataFrame({'PassengerId': test_df.PassengerId,
                       'Survived': predictions})
output.to_csv('submission_v3.csv', index=False)