# -*- coding: utf-8 -*-
"""metric_celection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zz8AYhgCc2m__FFuCOdV_T-ZEr-Zb2Xk
"""

import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import KFold
from sklearn.datasets import load_boston
from sklearn.preprocessing import scale
from sklearn.model_selection import cross_val_score

boston = load_boston()
x, y = boston['data'], boston['target']
x = scale(x)

p = np.linspace(1, 10, 200)
kfold = KFold(n_splits=5, shuffle=True, random_state=42)
arr = []
for i in p:
    model = KNeighborsRegressor(p=i, n_neighbors=5, weights='distance')
    scores = cross_val_score(model, x, y, cv=kfold, scoring='neg_mean_squared_error')
    arr.append(scores)
df = pd.DataFrame(arr, p).max(axis=1).sort_values(ascending=False)
df.head(1)