# -*- coding: utf-8 -*-
"""random_forest.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yIQ9DM85PFRAYrqP4TfCwTVY_WHC0XvE
"""

import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import KFold, cross_val_score
from sklearn.metrics import r2_score

df = pd.read_csv('abalone.csv')

df['Sex'] = df['Sex'].map(lambda x: 1 if x == 'M' else (-1 if x == 'F' else 0))

y = df['Rings']
x = df.drop(['Rings'], axis=1)

kf = KFold(n_splits=5, shuffle=True, random_state=1)

arr = []
for i in range(1, 51):
    rf_model = RandomForestRegressor(n_estimators=i, random_state=1)
    rf_model.fit(x, y)
    score = cross_val_score(rf_model, x, y, cv=kf, scoring='r2')
    arr.append(score.mean())
arr