# -*- coding: utf-8 -*-
"""first_lesson_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q3FG4zU0BnQmfvKZpFYS7lh5M_223P1s
"""

import pandas as pd
reviews = pd.read_csv("winemag-data_first150k.csv", index_col=0)
reviews.head()

reviews[reviews['price'] < 100].sample(100).plot.scatter(x='price', y='points')

reviews[reviews['price'] < 100].plot.scatter(x='price', y='points')

reviews[reviews['price'] < 100].plot.hexbin(x='price', y='points', gridsize=20)

wine_counts = pd.read_csv("top-five-wine-score-counts.csv",
                          index_col=0)
wine_counts.head()

wine_counts.plot.bar(stacked=True)

wine_counts.plot.area()

wine_counts.plot.line()