# -*- coding: utf-8 -*-
"""first_lesson_home_work_4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tLbBIj0ICZFxDWz8FeJ41rI1h-dxLFKu
"""

import pandas as pd
import seaborn as sns

pokemon = pd.read_csv("Pokemon.csv", index_col=0)
pokemon.head(3)

g = sns.FacetGrid(pokemon, row="Legendary")
g.map(sns.kdeplot, "Attack")

g = sns.FacetGrid(pokemon, col='Legendary', row="Generation")
g.map(sns.kdeplot, "Attack")

sns.pairplot(pokemon[['HP', 'Attack', 'Defense']])