# -*- coding: utf-8 -*-
"""first_lesson_home_work.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PVVO1igVgJscoyM-L920zplIXvlcfX5H
"""

import pandas as pd
pd.set_option('max_columns', None)
pokemon = pd.read_csv('pokemon.csv')
pokemon.head(3)

pokemon['type1'].value_counts().plot.bar()

pokemon['hp'].value_counts().sort_index().plot.line()

pokemon['weight_kg'].plot.hist()