# -*- coding: utf-8 -*-
"""first_lesson_home_work_1_multivariate.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BoPH_04f3PiC1RyswCJFqnUGrfregNj6
"""

import pandas as pd
import seaborn as sns
pokemon = pd.read_csv("Pokemon.csv", index_col=0)
pokemon.head()

sns.lmplot(x='Attack', y='Defense', hue='Legendary', 
           data=pokemon,
           markers=['x', 'o'],
           fit_reg=False)

sns.boxplot(x='Generation', y='Total', hue='Legendary', data=pokemon)

sns.heatmap(pokemon.loc[:, ['HP', 'Attack', 'Sp. Atk', 'Defense', 'Sp. Def', 'Speed']].corr(), annot=True)

from pandas.plotting import parallel_coordinates

p = (pokemon[(pokemon['Type 1'].isin(["Psychic", "Fighting"]))]
         .loc[:, ['Type 1', 'Attack', 'Sp. Atk', 'Defense', 'Sp. Def']]
    )

parallel_coordinates(p, 'Type 1')