# -*- coding: utf-8 -*-
"""first_lesson_home_work_1_styling.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HhLIj6oQC31kro9C2hv2M7tgsjY2vEKR
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

pokemon = pd.read_csv("Pokemon.csv")
pokemon.head(3)

pokemon.plot.scatter(x='Attack', y='Defense', title='Pokemon by Attack and Defense', figsize=(12, 6))

ax = pokemon['Total'].plot.hist(
    figsize=(12, 6),
    fontsize=14,
    bins=50,
    color='gray'
)
ax.set_title('Pokemon by Stat Total', fontsize=20)

ax = pokemon['Type 1'].value_counts().plot.bar(
    figsize=(12, 6),
    fontsize=14
)
ax.set_title("Pokemon by Primary Type", fontsize=20)
sns.despine(bottom=True, left=True)