# -*- coding: utf-8 -*-
"""first_lesson_home_work_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1deezgcqbU6XgnBdNMc1SFe31K4q3-2kY
"""

import pandas as pd
pokemon = pd.read_csv("Pokemon.csv", index_col=0)
pokemon.head()

pokemon.plot.scatter(x='Attack', y='Defense')

pokemon.plot.hexbin(x='Attack', y='Defense', gridsize=20)

pokemon_stats_legendary = pokemon.groupby(['Legendary', 'Generation']).mean()[['Attack', 'Defense']]
pokemon_stats_legendary.plot.bar(stacked=True)

pokemon_stats_by_generation = pokemon.groupby('Generation').mean()[['HP', 'Attack', 'Defense', 'Sp. Atk', 'Sp. Def', 'Speed']]
pokemon_stats_by_generation.plot.line()