# -*- coding: utf-8 -*-
"""first_lesson_1_styling.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-kEQoqsmmyoeB3sbBKflS-JrMx-_spTV
"""

import pandas as pd
reviews = pd.read_csv('winemag-data_first150k.csv', index_col=0)
reviews.head(3)

reviews['province'].value_counts().head(10).plot.bar()

(reviews['province'].value_counts().head(10) / len(reviews)).plot.bar()

reviews['points'].value_counts().sort_index().plot.bar()

reviews['points'].value_counts().sort_index().plot.line()

reviews['points'].value_counts().sort_index().plot.area()

reviews[reviews['price'] < 200]['price'].plot.hist()

reviews['price'].plot.hist()

reviews[reviews['price'] > 1500]

reviews['points'].plot.hist()

reviews['points'].value_counts().sort_index().plot.bar(figsize=(20, 10))

reviews['points'].value_counts().sort_index().plot.bar(
    figsize=(12, 6),
    color='mediumvioletred'
)

reviews['points'].value_counts().sort_index().plot.bar(
    figsize=(12, 6),
    color='mediumvioletred',
    fontsize=16
)

reviews['points'].value_counts().sort_index().plot.bar(
    figsize=(12, 6),
    color='mediumvioletred',
    fontsize=16,
    title='Rankings Given by Wine Magazine',
)

import matplotlib.pyplot as plt

ax = reviews['points'].value_counts().sort_index().plot.bar(
    figsize=(12, 6),
    color='mediumvioletred',
    fontsize=16
)
ax.set_title("Rankings Given by Wine Magazine", fontsize=20)

import matplotlib.pyplot as plt
import seaborn as sns

ax = reviews['points'].value_counts().sort_index().plot.bar(
    figsize=(12, 6),
    color='mediumvioletred',
    fontsize=16
)
ax.set_title("Rankings Given by Wine Magazine", fontsize=20)
sns.despine(bottom=True, left=True)

