# -*- coding: utf-8 -*-
"""first_lesson.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1evSnq16eQdG9mOWn8Q3vjHDIEwy0E6EJ
"""

import pandas as pd
reviews = pd.read_csv('winemag-data_first150k.csv', index_col=0)
reviews.head(3)

reviews['province'].value_counts().head(10).plot.bar()

(reviews['province'].value_counts().head(10) / len(reviews)).plot.bar()

reviews['points'].value_counts().sort_index().plot.bar()

reviews['points'].value_counts().sort_index().plot.line()

reviews['points'].value_counts().sort_index().plot.area()

reviews[reviews['price'] < 200]['price'].plot.hist()

reviews['price'].plot.hist()

reviews[reviews['price'] > 1500]

reviews['points'].plot.hist()